# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tameez
subtitle: Train your ear to distinguish Arabic sounds.
email: jakub AT szypulka.de
baseurl: "/tameez" # the subpath of your site, e.g. /blog
url: "jaksz.github.io" # the base hostname & protocol for your site
github_username:  jaksz/tameez

# Build settings
markdown: kramdown

# Collections
collections:
  arabic:
    output: true
